### ISSUE TITLE
Cannot start server, cannot find ensime file

### ISSUE THREAD

**Issue by fredc0088** [dragos/dragos-vscode-scala#46] opened 2017-06-13 15:53 UTC
Hi. I am experiencing some issue while trying to make the extension works. I have created a new build with ensimeConfigProject, and created the structure src>main>scala. I still receive "no .ensime file in directory. Run `sbt ensimeConfig` to create one." when opening a scala file, obviously no auto-competition or any other feature is working.  I believe the issue was there even with .ensime in the root. What could be the cause? How can I make the extension work?

Here is mine pc.stdout

[pc.stdout.txt](https://github.com/dragos/dragos-vscode-scala/files/1072345/pc.stdout.txt)

and mine ensime-langserver

[ensime-langserver.txt](https://github.com/dragos/dragos-vscode-scala/files/1072356/ensime-langserver.txt)

I also tried with a new configuration and then ensimeLaunch

here is the error i get:

    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
[error] (compile:ensimeLaunch) scala.MatchError: List() (of class scala.collection.immutable.Nil$)
[error] Total time: 1 s, completed 13-Jun-2017 18:23:02

Thanks, I appreciate any help

**Comment by fredc0088** [comment] 2017-06-13 17:25
I also tried with a new configuration and then ensimeLaunch

here is the error i get:

        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[error] (compile:ensimeLaunch) scala.MatchError: List() (of class scala.collection.immutable.Nil$)
[error] Total time: 1 s, completed 13-Jun-2017 18:23:02

**Comment by dragos** [comment] 2017-06-14 07:54
In the logs:

```
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by another program: /Users/Fred88/Documents/repos/BirkBeck_Prep/src/Scala/ScalaTutorial/.ensime_cache/index-2.0.3g/write.lock
```

Just delete the lock file. Probably an earlier crash left that file in there.

**Comment by fredc0088** [comment] 2017-06-14 08:31
Thanks for the reply.
I did it, but still it keeps encuntering different errors. 
this a constant error though: 

[2017-06-14 09:25:35,807] ERROR langserver.core.Connection - No notification type exists with method=initialized

[ensime-langserver.txt](https://github.com/dragos/dragos-vscode-scala/files/1073982/ensime-langserver.txt)

[pc.stdout.txt](https://github.com/dragos/dragos-vscode-scala/files/1073984/pc.stdout.txt)

**Comment by dragos** [comment] 2017-06-14 08:43
Oh, this error is a duplicate of #45 We should get a fix upstream this weekend, it seems.

**Comment by fredc0088** [comment] 2017-06-14 12:14
Ok, I see. I will wait the fix this weekend and try again. Thanks a lot

**Comment by dragos** [comment] 2017-06-20 14:14
Please upgrade to 0.1.6, should be fixed

**Closed by dragos** 2017-06-20 14:14 UTC
